const quickmap=new Map(
[
    ['flex','display:flex'],
    ['grid','display:grid'],
    ['block','display:block'],
    ['inlineBlock','display:inline-block'],
    ['static','position:static'],
    ['relative','position:relative'],
    ['absolute','position:absolute'],
    ['fixed','position:fixed'],
    ['sticky','position:sticky'],
    ['textLeft','text-align:left'],
    ['textRight','text-align:right'],
    ['textCenter','text-align:center'],
    ['w','width'],
    ['h','height'],
    ['maxW','max-width'],
    ['maxH','max-height'],
    ['minW','min-width'],
    ['minH','min-height'],
    ['m','margin'],
    ['p','padding'],
    ['mt','margin-top'],
    ['mb','margin-bottom'],
    ['ml','margin-left'],
    ['mr','margin-right'],
    ['pt','padding-top'],
    ['pb','padding-bottom'],
    ['pl','padding-left'],
    ['pr','padding-right'],
    ['bg','background'],
]
);
const prefixmap=new Map([
    ['sm','@media (min-width:640px)'],
    ['md','@media (min-width:768px)'],
    ['lg','@media (min-width:1024px)'],
    ['dark','@media (prefers-color-scheme:dark)'],
    ['hover','hover'],
    ['active','active'],
    ['focus','focus'],
    ['focusWithin','focus-within'],
    ['visited','visited'],
    ['checked','checked'],
    ['first','first'],
    ['last','last'],
    ['even','even'],
    ['odd','odd'],
]);

module.exports={quickmap,prefixmap};